import React from "react"
import { PageProps, graphql } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

type Data = {
  site: {
    siteMetadata: {
      title: string
      siteUrl: string
    }
  }
}

const Imprint = ({ data, location }: PageProps<Data>) => {
  const site = data.site.siteMetadata

  return (
    <Layout location={location} title={site.title}>
      <SEO title="Privacy" />
      <h1>Privacy Policy</h1>
      <p>Last updated: 2020-05-29</p>
      <p>
        {site.title} ("us", "we", or "our") operates {site.siteUrl} (the
        "Site"). This page informs you of our policies regarding the collection,
        use and disclosure of Personal Information we receive from users of the
        Site.
      </p>
      <p>
        We use your Personal Information only for providing and improving the
        Site. By using the Site, you agree to the collection and use of
        information in accordance with this policy.
      </p>
      <h2>Information Collection And Use</h2>
      <p>
        While using our Site, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you. Personally identifiable information may include, but is
        not limited to your name and email address ("Personal Information").
      </p>
      <h2>Google Analytics (with anonymization function)</h2>
      <p>
        We use Google Analytics (with anonymization function), a web analytics
        service provided by Google Inc. ("Google"). Google Analytics uses
        cookies which permit an analysis of your use of the website. The
        information about your website use generated by the cookie (including
        your truncated IP address) is transmitted to a server controlled by
        Google in the USA and is stored there. Google uses this information to
        analyze your use of the website, to generate reports about website
        activities for website operators, and to provide further services
        related to website and internet use. Google may also share such
        information with third parties to the extent it is legally required to
        do so and/or to the extent third parties process data on behalf of
        Google.
      </p>
      <p>
        You can find detailed information about how Google uses your data in{" "}
        <a href="https://www.google.com/policies/privacy/">
          Google’s privacy policy
        </a>
        .
      </p>
      <p>
        We use Google Analytics with the anonymization function. By means of
        this addition, Google shortens and anonymizes the IP address of the
        Internet connection of the person concerned, if our Internet pages are
        accessed from a member state of the European Union or from another state
        party to the Agreement on the European Economic Area.
      </p>
      <p>
        You may deactivate Google Analytics with the help of a browser add-on if
        you do not want this website analysis. This add-on can be downloaded{" "}
        <a href="https://tools.google.com/dlpage/gaoptout?hl=en">here</a>. You
        can also activate the "I refuse the storage of my user profile" option
        above, which will deactivate the Google Analytics service on our website
        in your browser.
      </p>
      <p>
        User-based event data at Google Analytics is deleted after 38 months.
      </p>
      <h2>Cookies</h2>
      <p>
        Cookies are files with small amount of data, which may include an
        anonymous unique identifier. Cookies are sent to your browser from a web
        site and stored on your computer's hard drive.
      </p>
      <p>
        Like many sites, we use "cookies" to collect information. You can
        instruct your browser to refuse all cookies or to indicate when a cookie
        is being sent. However, if you do not accept cookies, you may not be
        able to use some portions of our Site.
      </p>
      <h2>Security</h2>
      <p>
        The security of your Personal Information is important to us, but
        remember that no method of transmission over the Internet, or method of
        electronic storage, is 100% secure. While we strive to use commercially
        acceptable means to protect your Personal Information, we cannot
        guarantee its absolute security.
      </p>
      <h2>Changes To This Privacy Policy</h2>
      <p>
        This Privacy Policy is effective as of (add date) and will remain in
        effect except with respect to any changes in its provisions in the
        future, which will be in effect immediately after being posted on this
        page.
      </p>
      <p>
        We reserve the right to update or change our Privacy Policy at any time
        and you should check this Privacy Policy periodically. Your continued
        use of the Service after we post any modifications to the Privacy Policy
        on this page will constitute your acknowledgment of the modifications
        and your consent to abide and be bound by the modified Privacy Policy.
      </p>
      <p>
        If we make any material changes to this Privacy Policy, we will notify
        you either through the email address you have provided us, or by placing
        a prominent notice on our website.
      </p>
      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please{" "}
        <a href="mailto:hello@richartkeil.com" target="_blank">
          contact us
        </a>
        .
      </p>
    </Layout>
  )
}

export default Imprint

export const pageQuery = graphql`
  query {
    site {
      siteMetadata {
        title
        siteUrl
      }
    }
  }
`
